#!/bin/sh

PYTHONPATH="/project2/lbarreiro/programs/bioluigi/:/project2/lbarreiro/programs/rasqual/"
PATH=$PATH:/project2/lbarreiro/programs/tabix-0.2.6.tar/tabix-0.2.6/
export PATH
module load python/3.7.0
module load STAR
module load gatk/3.7
module load bedtools
/project2/lbarreiro/programs/luigi/bin/luigi --module luigi_pipeline.RASQUAL_l --local-scheduler $@
